repos:
  - repo: local
    hooks:
      - id: just-format
        name: Format files
        entry: just format
        language: system
        pass_filenames: false
        always_run: true
        
      - id: just-embedme
        name: Embed examples in README
        entry: just embedme
        language: system
        pass_filenames: false
        always_run: true
