repos:
  - repo: local
    hooks:
      - id: just-format
        name: Format files
        entry: just format
        language: system
        pass_filenames: false
        always_run: true

      - id: just-embedme
        name: Embed examples in README
        entry: just embedme
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
