name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  embedme:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check embedme
        run: |
          npm install -g embedme
          embedme --verify README.md
